{ Generated by scripts\fetch-presets.ps1 (#299). Do not edit by hand. }
{ }
{ Holds the pinned release tag, download URLs and SHA-256 hashes of the }
{ optional projectM preset packs. Re-run the script to refresh it: }
{   scripts\fetch-presets.ps1 -ReleaseTag viz-presets-<yyyymmdd> -Archive }
{ }
{ The empty values below are the committed placeholders: a normal developer }
{ build bundles the base set but offers no downloads until a release run }
{ regenerates this file. The indices match the pack table in presets.iss. }
const
  PresetReleaseTag = 'unreleased';

function PresetArchiveUrlOf(Index: Integer): String;
begin
  case Index of
    0: Result := '';
    1: Result := '';
    2: Result := '';
  else
    Result := '';
  end;
end;

function PresetArchiveSha256Of(Index: Integer): String;
begin
  case Index of
    0: Result := '';
    1: Result := '';
    2: Result := '';
  else
    Result := '';
  end;
end;
